export const BANK_COLOR_OPTIONS = [
  { label: "ABN AMRO", value: "#FFD100" },
  { label: "Banco Santander", value: "#EC0000" },
  { label: "Bank of America", value: "#012169" },
  { label: "Barclays", value: "#00AEEF" },
  { label: "BNP Paribas", value: "#00966C" },
  { label: "CaixaBank", value: "#0065A4" },
  { label: "Capital One", value: "#004977" },
  { label: "Citibank", value: "#1A4CA1" },
  { label: "Commerzbank", value: "#FFCC00" },
  { label: "Credit Suisse", value: "#003263" },
  { label: "Crédit Agricole", value: "#019B6A" },
  { label: "Danske Bank", value: "#0055A5" },
  { label: "Deutsche Bank", value: "#0018A8" },
  { label: "Goldman Sachs", value: "#1A4CA1" },
  { label: "Halifax", value: "#0072CE" },
  { label: "HSBC", value: "#DB0011" },
  { label: "ING", value: "#FF6200" },
  { label: "Intesa Sanpaolo", value: "#008C45" },
  { label: "JPMorgan Chase", value: "#117ACA" },
  { label: "KBC", value: "#009FE3" },
  { label: "Lloyds Bank", value: "#005A42" },
  { label: "Metro Bank", value: "#E41F26" },
  { label: "Morgan Stanley", value: "#2A4D9B" },
  { label: "NatWest", value: "#7A297B" },
  { label: "Nordea", value: "#002C77" },
  { label: "PNC", value: "#FF8200" },
  { label: "Rabobank", value: "#FF8000" },
  { label: "Reiffeisen Bank", value: "#FFD600" },
  { label: "Royal Bank of Canada (RBC)", value: "#0033A0" },
  { label: "Royal Bank of Scotland (RBS)", value: "#003366" },
  { label: "Santander", value: "#EC0000" },
  { label: "Scotiabank", value: "#EC111A" },
  { label: "Société Générale", value: "#E2231A" },
  { label: "Swedbank", value: "#FFB511" },
  { label: "TD Bank", value: "#53A546" },
  { label: "TSB", value: "#1D70B8" },
  { label: "UBS", value: "#E0001B" },
  { label: "UniCredit", value: "#E31837" },
  { label: "US Bank", value: "#005195" },
  { label: "Wells Fargo", value: "#C40404" },
];
